CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    avatar VARCHAR(500),
    nick_name VARCHAR(50),
    gender INT DEFAULT 0,
    dept_id BIGINT,
    status INT DEFAULT 1,
    is_admin INT DEFAULT 0,
    last_login_ip VARCHAR(50),
    last_login_time TIMESTAMP,
    pwd_reset_time TIMESTAMP,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_username ON sys_user(username);

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    data_scope INT DEFAULT 1,
    status INT DEFAULT 1,
    sort_oder INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_role_code ON sys_role(role_code);

CREATE TABLE IF NOT EXISTS sys_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perm_code VARCHAR(100) NOT NULL,
    perm_name VARCHAR(100) NOT NULL,
    resource_type VARCHAR(20),
    resource_path VARCHAR(255),
    parent_id BIGINT DEFAULT 0,
    sort_oder INT DEFAULT 0,
    icon VARCHAR(50),
    status INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_permission_code ON sys_permission(perm_code);

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_role ON sys_user_role(user_id, role_id);

CREATE TABLE IF NOT EXISTS sys_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_role_permission ON sys_role_permission(role_id, permission_id);

CREATE TABLE IF NOT EXISTS data_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) NOT NULL,
    type VARCHAR(30) NOT NULL,
    host VARCHAR(200),
    port INT,
    `database` VARCHAR(100),
    service VARCHAR(100),
    url VARCHAR(500),
    username VARCHAR(100),
    password_encrypted VARCHAR(500),
    driver_class VARCHAR(200),
    config_json CLOB,
    status INT DEFAULT 1,
    health_status INT DEFAULT 0,
    last_check_time TIMESTAMP,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_data_source_code ON data_source(code);

CREATE TABLE IF NOT EXISTS ai_runtime_setting (
    id BIGINT PRIMARY KEY,
    enabled INT DEFAULT 0,
    default_provider VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_provider_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_key VARCHAR(50) NOT NULL,
    provider_name VARCHAR(100),
    api_url VARCHAR(255),
    api_key_encrypted CLOB,
    model VARCHAR(100),
    temperature DOUBLE DEFAULT 0.7,
    max_tokens INT DEFAULT 2000,
    enabled INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_provider_setting_key ON ai_provider_setting(provider_key);

CREATE TABLE IF NOT EXISTS metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    definition CLOB,
    data_type VARCHAR(20),
    data_source_id BIGINT,
    table_name VARCHAR(100),
    field_name VARCHAR(100),
    aggregation VARCHAR(20),
    cube_sql CLOB,
    dimensions CLOB,
    measures CLOB,
    status VARCHAR(20) DEFAULT 'active',
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_metrics_code ON metrics(code);

CREATE TABLE IF NOT EXISTS synonyms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    standard_word VARCHAR(100) NOT NULL,
    aliases VARCHAR(2000),
    description VARCHAR(255),
    status INT DEFAULT 1,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_synonyms_standard_word ON synonyms(standard_word);

CREATE TABLE IF NOT EXISTS prompt_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    version_tag VARCHAR(100) NOT NULL,
    template CLOB NOT NULL,
    variables CLOB,
    status VARCHAR(20) DEFAULT 'draft',
    gray_scale_percent INT DEFAULT 0,
    description VARCHAR(500),
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_prompt_version_tag ON prompt_version(version_tag);

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64),
    conversation_id VARCHAR(64),
    user_id BIGINT,
    question CLOB,
    generated_sql CLOB,
    rating INT DEFAULT 0,
    correct_sql CLOB,
    comment CLOB,
    exported BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_feedback_message_id ON feedback(message_id);
CREATE INDEX IF NOT EXISTS idx_feedback_conversation_id ON feedback(conversation_id);
CREATE INDEX IF NOT EXISTS idx_feedback_exported ON feedback(exported);

CREATE TABLE IF NOT EXISTS query_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(50),
    query_name VARCHAR(100),
    query_type VARCHAR(30),
    query_content CLOB,
    datasource_id BIGINT,
    result_data CLOB,
    duration BIGINT,
    status VARCHAR(20),
    error_msg CLOB,
    is_favorite BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS data_permission_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(100) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    role_id BIGINT,
    user_id BIGINT,
    operator_symbol VARCHAR(20) NOT NULL,
    rule_value VARCHAR(500),
    value_type VARCHAR(20) DEFAULT 'CONSTANT',
    priority INT DEFAULT 1,
    status INT DEFAULT 1,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS data_masking_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(100) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    role_id BIGINT,
    user_id BIGINT,
    mask_type VARCHAR(20) DEFAULT 'PARTIAL',
    mask_pattern VARCHAR(100),
    priority INT DEFAULT 1,
    status INT DEFAULT 1,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    type VARCHAR(20) NOT NULL,
    resource_id BIGINT NOT NULL,
    subscriber_id BIGINT,
    subscriber_name VARCHAR(100),
    push_method VARCHAR(20),
    receiver VARCHAR(255),
    frequency VARCHAR(20),
    push_time VARCHAR(10),
    push_day VARCHAR(20),
    status INT DEFAULT 1,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_push_time TIMESTAMP,
    push_count INT DEFAULT 0,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS share (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    type VARCHAR(20) NOT NULL,
    resource_id BIGINT NOT NULL,
    share_token VARCHAR(32) NOT NULL,
    share_method VARCHAR(20),
    validity_type VARCHAR(20),
    validity_days INT,
    expire_time TIMESTAMP,
    password VARCHAR(100),
    max_visits INT,
    current_visits INT DEFAULT 0,
    status INT DEFAULT 1,
    created_by BIGINT,
    creator_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS embedded_access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_id BIGINT NOT NULL,
    share_token VARCHAR(64) NOT NULL,
    origin VARCHAR(255),
    visitor_key VARCHAR(255),
    ip_address VARCHAR(64),
    user_agent VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    customer_name VARCHAR(100),
    product_id BIGINT NOT NULL,
    product_name VARCHAR(200),
    product_category VARCHAR(50),
    region VARCHAR(50),
    sales_person_id BIGINT,
    sales_person_name VARCHAR(100),
    quantity INT,
    unit_price DECIMAL(15, 2),
    sales_amount DECIMAL(15, 2),
    cost_amount DECIMAL(15, 2),
    profit_amount DECIMAL(15, 2),
    discount_amount DECIMAL(15, 2) DEFAULT 0,
    order_date DATE NOT NULL,
    delivery_date DATE,
    status VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sales_order_no ON sales_order(order_no);

CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_no VARCHAR(50) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    customer_type VARCHAR(20),
    industry VARCHAR(50),
    region VARCHAR(50),
    level VARCHAR(20),
    contact_person VARCHAR(100),
    contact_phone VARCHAR(50),
    email VARCHAR(100),
    first_purchase_date DATE,
    last_purchase_date DATE,
    total_purchase_amount DECIMAL(15, 2) DEFAULT 0,
    purchase_count INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_customer_no ON customer(customer_no);

CREATE TABLE IF NOT EXISTS user_behavior (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id VARCHAR(100),
    event_type VARCHAR(50) NOT NULL,
    page_url VARCHAR(500),
    page_title VARCHAR(200),
    referrer VARCHAR(500),
    device_type VARCHAR(20),
    os VARCHAR(50),
    browser VARCHAR(50),
    channel VARCHAR(50),
    duration INT,
    ip_address VARCHAR(50),
    city VARCHAR(50),
    province VARCHAR(50),
    event_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_no VARCHAR(50) NOT NULL,
    username VARCHAR(100),
    nickname VARCHAR(100),
    gender VARCHAR(10),
    age INT,
    city VARCHAR(50),
    province VARCHAR(50),
    register_channel VARCHAR(50),
    register_date DATE,
    last_login_date DATE,
    login_count INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_app_user_no ON app_user(user_no);

CREATE TABLE IF NOT EXISTS financial_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no VARCHAR(50) NOT NULL,
    record_date DATE NOT NULL,
    category VARCHAR(50) NOT NULL,
    sub_category VARCHAR(50),
    amount DECIMAL(15, 2) NOT NULL,
    type VARCHAR(20) NOT NULL,
    department VARCHAR(50),
    project_id BIGINT,
    project_name VARCHAR(200),
    description CLOB,
    status VARCHAR(20) DEFAULT 'CONFIRMED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_financial_record_no ON financial_record(record_no);

CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(200),
    product_category VARCHAR(50),
    warehouse VARCHAR(50),
    quantity INT,
    unit_cost DECIMAL(15, 2),
    total_value DECIMAL(15, 2),
    safety_stock INT,
    last_in_date DATE,
    last_out_date DATE,
    status VARCHAR(20) DEFAULT 'NORMAL',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_no VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    customer_name VARCHAR(100),
    ticket_type VARCHAR(50),
    priority VARCHAR(20),
    status VARCHAR(20),
    channel VARCHAR(50),
    subject VARCHAR(200),
    assignee_id BIGINT,
    assignee_name VARCHAR(100),
    created_date TIMESTAMP NOT NULL,
    first_response_date TIMESTAMP,
    resolved_date TIMESTAMP,
    response_time_minutes INT,
    resolution_time_hours DECIMAL(10, 2),
    satisfaction_score INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_service_ticket_no ON service_ticket(ticket_no);

CREATE TABLE IF NOT EXISTS project_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(50) NOT NULL,
    project_name VARCHAR(200) NOT NULL,
    owner_team VARCHAR(100),
    region VARCHAR(50),
    planned_delivery_date DATE NOT NULL,
    actual_delivery_date DATE,
    delivery_status VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_project_delivery_code ON project_delivery(project_code);

CREATE TABLE IF NOT EXISTS approval_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_no VARCHAR(50) NOT NULL,
    department VARCHAR(50) NOT NULL,
    process_type VARCHAR(50),
    applicant_name VARCHAR(100),
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    duration_hours DECIMAL(10, 2),
    status VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_approval_record_no ON approval_record(approval_no);

CREATE TABLE IF NOT EXISTS agile_story (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    sprint_id BIGINT,
    story_code VARCHAR(50) NOT NULL,
    story_title VARCHAR(500) NOT NULL,
    story_type VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    story_points INT,
    assignee_id BIGINT,
    reporter_id BIGINT,
    estimated_hours DECIMAL(10, 2),
    actual_hours DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_agile_story_code ON agile_story(story_code);

CREATE TABLE IF NOT EXISTS agile_team_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    username VARCHAR(100) NOT NULL,
    real_name VARCHAR(100),
    role VARCHAR(50) NOT NULL,
    department VARCHAR(100),
    email VARCHAR(200),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    join_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_agile_team_user_id ON agile_team_member(user_id);
