package com.chatbi.service;

import com.chatbi.entity.Metric;
import com.chatbi.repository.MetricMapper;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Spy;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;

/**
 * MetricCube 查询服务测试（Headless BI）
 */
@ExtendWith(MockitoExtension.class)
class MetricCubeServiceTest {

    @Mock
    private MetricMapper metricMapper;

    @Spy
    private ObjectMapper objectMapper = new ObjectMapper();

    @InjectMocks
    private MetricCubeService metricCubeService;

    @Test
    void tryResolve_shouldReturnCubeSql_whenMetricMatchedWithCubeSql() {
        Metric metric = Metric.builder()
                .id(1L)
                .name("销售额")
                .status("active")
                .cubeSql("SELECT {{dimension}}, SUM(`amount`) AS `销售额_result` FROM `sales` WHERE {{timeFilter}} GROUP BY {{dimension}} LIMIT 100")
                .columnName("amount")
                .tableName("sales")
                .aggregation("SUM")
                .dimensions("[{\"field\":\"region\",\"name\":\"地区\"},{\"field\":\"created_at\",\"name\":\"时间\"}]")
                .build();

        when(metricMapper.selectList(null)).thenReturn(List.of(metric));

        String sql = metricCubeService.tryResolve("本月各地区销售额");

        assertNotNull(sql);
        assertTrue(sql.contains("SUM(`amount`)"));
        assertTrue(sql.contains("`region`"));
        assertTrue(sql.contains("LIMIT 100"));
    }

    @Test
    void tryResolve_shouldReturnAutoGeneratedSql_whenMetricHasNoCubeSql() {
        Metric metric = Metric.builder()
                .id(1L)
                .name("订单量")
                .status("active")
                .columnName("id")
                .tableName("orders")
                .aggregation("COUNT")
                .build();

        when(metricMapper.selectList(null)).thenReturn(List.of(metric));

        String sql = metricCubeService.tryResolve("本月订单量");

        assertNotNull(sql);
        assertTrue(sql.contains("COUNT(`id`)"));
        assertTrue(sql.contains("`orders`"));
    }

    @Test
    void tryResolve_shouldReturnNull_whenNoMetricMatched() {
        when(metricMapper.selectList(null)).thenReturn(List.of());

        String sql = metricCubeService.tryResolve("随便问个问题");

        assertNull(sql);
    }

    @Test
    void parseTimeFilter_shouldRecognize_thisMonth() {
        MetricCubeService.TimeFilter filter = metricCubeService.parseTimeFilter("本月销售额");
        assertFalse(filter.sql().isBlank());
        assertTrue(filter.sql().contains("MONTH"));
    }

    @Test
    void parseTimeFilter_shouldRecognize_last7Days() {
        MetricCubeService.TimeFilter filter = metricCubeService.parseTimeFilter("最近7天销售额");
        assertFalse(filter.sql().isBlank());
        assertTrue(filter.sql().contains("DATEADD('DAY', -7"));
    }

    @Test
    void parseTimeFilter_shouldReturnEmpty_whenNoTimeExpr() {
        MetricCubeService.TimeFilter filter = metricCubeService.parseTimeFilter("销售额总和");
        assertTrue(filter.sql().isBlank());
    }
}
